"""add extra_context and user_instructions to content_items

Revision ID: fba124e07d9b
Revises: 0001
Create Date: 2026-05-24 09:32:15.267091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba124e07d9b'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('extra_context', sa.Text(), nullable=True))
    op.add_column('content_items', sa.Column('user_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'user_instructions')
    op.drop_column('content_items', 'extra_context')
    # ### end Alembic commands ###
